package leCampusServerTest;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import leCampusServer.ServerApplication;
//import spock.lang.Specification;

import static org.junit.Assert.*;

public class LeCampusServerTest {
    @Test 
    public void testSomeLibraryMethod() {
        ServerApplication classUnderTest = new ServerApplication();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
