package leCampusServer;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;

import leCampusServer.domain.Member;
import leCampusServer.repository.MemberRepository;
import leCampusServer.service.MemberService;

import org.springframework.beans.factory.annotation.Autowired;

@SpringBootApplication
public class ServerApplication extends WebMvcConfigurerAdapter implements CommandLineRunner {

	@Autowired MemberRepository memberRepository;
    
	public static void main (String[] args) {
		SpringApplication.run(ServerApplication.class, args);
	}
	
	@Override
	public void run (String... args) throws Exception {
		
	}
	
}
